### ISSUE TITLE
[FEATURE] Skill Template that auto-locks skills.

### ISSUE THREAD

**Issue by eruspravus** [markdwags/Razor#122] opened 2020-09-17 12:14 UTC
This was suggested to me from a guild friend.

The ability to setup your skill-template in Razor and allow razor to automatically set skills and stats locks to match that template.

Ex; You enter that you want 80 Magery. But your Magery is only 50 so it auto switch it to UP, once skill reach 80 it auto locks it.
The auto-lock feature should probably be optional (checkbox).

The only way to do anything similar today is when training with Macros and then you can do some 'if skill >= value; stop macro' stuff. But it quickly becomes complicated if you doing multiple skills at once (support skills like Anatomy or Eval for example).
Also its no help at all for Naturalists that dont macro.

I really liked the idea and promised to forward it. But I have to admit it sound like a bit of a hassle to implement. ;)

**Comment by markdwags** [comment] 2020-09-17 14:59
I've had a few requests asking for a feature to lock/unlock skills from a macro or script. Let me think on this one a bit, because as you state, it can be done using some if statements and some macro trickery.

**Comment by markdwags** [comment] 2020-10-12 19:56
Duplicate of #100

**Comment by markdwags** [comment] 2021-01-27 18:41
Closing duplicate

**Closed as completed by markdwags** 2021-01-27 18:41 UTC
Labels: enhancement, unsure
