### ISSUE TITLE
[BUG] Next Friendly & Next Non-Friendly sets both Beneficial and Harmful

### ISSUE THREAD

**Issue by BlackTeaOutlands** [markdwags/Razor#47] opened 2019-07-13 23:35 UTC
I'm using ClassicUO.

In order to use smart target, you need to be able to efficiently set both Beneficial and Harmful targets. There are currently 70 different hotkeys that can be set for various targetting, but none of them do what is actually needed.

If you use Next Friendly Humanoid Target, it will set the target to both Beneficial and Harmful. If you use Next Non-friendly Humanoid Target, it will set the target to both Beneficial and Harmful.

I expect Next Friendly Humanoid Target (or any of the other options which imply you are cycling between friendly targets) to only set Beneficial. I expect Next Non-Friendly Humanoid target (or the other options which imply a non-friendly target), to only set Harmful.

This is the correct way to make Smart Target functional. You want complete control of who is assigned your Beneficial and who is assigned your Harmful flag.

A few more comments:
- The checkbox: "Only Next/Prev Friend" sets Beneficial, is not enough. Next Non-Friendly will still set your Non-Friendly target to Beneficial as well as Harmful. You also might want to use other options than Next/Prev Friend, for example Next Friendly Humanoid.
- If you want to set a Innocent or Guildmate as your Harmful target, that is still possible. Set Last Target should set both as Beneificial and Harmful. Anyone you manually cast a harmful spell on should be set as Harmful target. Anyone you manually cast a Beneficial spell on should be set as Beneficial target. You also have the option to hotkey Set Beneficial and Set Harmful.
- I think it worked as above mentioned for a few days, but the recent version seems to have had this reversed.
- To reiterate: It makes absolutely no sense to have Next Non-Friendly target set your target as both Beneficial and Harmful - what is the point of Smart Target then at all?

Thank you.

**Comment by markdwags** [comment] 2019-07-14 00:08
If you have "Only Next/Prev Friend sets Beneficial", then when you use Next Non-Friendly, or Next Friendly, it will only set Harmful.  Beneficial will always remain whatever target was set from Next/Prev Friend.

If you have "Only Next/Prev Friend sets Beneficial" unchecked, then yes, using any of the Next/Prev targets will reset Beneficial/Harmful to that target.  I cannot assume that someone using Next Friendly doesn't want that target to be set harmful, or someone using Next Non-Friendly doesn't want the target to be beneficial.

The only assumption I believe its safe to make is someone on your friends list should be set beneficial, and someone who isn't is considered harmful when using that checkbox.  With Set Harmful and Set Beneficial, that gives you the extra control to set who you want if one chooses.

Just to note, no changes have been made to targeting in 10 days, you can see changes here: https://github.com/markdwags/Razor/commits/master

_(changed from enhancement from bug, since Smart Targeting is working as intended and this is a request to change the feature.)_

**Comment by BlackTeaOutlands** [comment] 2019-07-14 00:14
1) It requires you to maintain a list of friends, which is far from optimal.

2) I think if someone uses smart target, you can safely assume that they do not want anything that they cycle with Next Friendly (or similar) to be set as Harmful. If a player wants their cycled targets to be set as both Harmful and Beneficial, then they can disable Smart Target. If Next Friendly only would set Beneficial, there are still multiple ways to manually set that target to Harmful, if you should so choose. I think the fact that Next Friendly sets both Beneficial and Harmful (and the same for Non-Friendly), it completely negates the purpose of Smart Target. Enabling Smart Target means that you choose to have full control of who is your Beneficial and who is your Harmful target, and if they are always (or almost always in the case of the 70 availible target hotkeys, set to both at the same time - Smart Target is not a useful feature).

I come from the dark ages of using old Razor. I know how it is to play without a proper targeting system. It is absolutely horrible and not compatible with an enjoyable PvP situation.

I'm not sure at all why it worked for a few days, but I guess it was a fluke then.

I really don't believe Smart Targeting is working as intended. If you don't want to change it, can I request a branch where it works as I (and Yu) suggested?

**Comment by BlackTeaOutlands** [comment] 2019-07-14 00:27
Compromise: Keep your version of "Smart Target" & Add another (working as stated above) called Smart Target Modified Version, or anything else that you choose to call it, you can hide it anywhere deep within options or even just availible in config files. Just as long as we get access to it somehow.

**Comment by BlackTeaOutlands** [comment] 2019-07-14 00:31
Yu also sent me a great suggestion here:

![image](https://user-images.githubusercontent.com/39037141/61177848-6a3a3380-a5df-11e9-8d35-22f6019350d5.png)

**Comment by BlackTeaOutlands** [comment] 2019-07-14 10:27
So thinking about it, I think you are right in a sense that sometimes you will want Next Friendly to set Harmful as well, specifically in the case of PKing. In the case of orange vs. orange PvP, however (which is just as, if not more frequent at least on Outlands), this is not the function you want. Then you want the function I described above.

I think Yu's suggestion in that screenshot would be the best overall, that way people get a lot of customizability to how their targetting hotkeys work.

**Comment by markdwags** [comment] 2019-07-19 05:43
Resolved with https://github.com/markdwags/Razor/commit/9e52199b8ea5f3e4e266240a18e6da7bc6b3c2c3

**Closed as completed by markdwags** 2019-07-19 05:43 UTC
Labels: enhancement
