### ISSUE TITLE
Organiser does not work from deeper level containers to backpack

### ISSUE THREAD

**Issue by dissident76** [markdwags/Razor#86] opened 2020-03-30 07:31 UTC
items will not be organised (razor says "Organize Agent did not find any items to move) if they are inside a container which is contained any levels below and inside the hot bag (organiser receiver). Or put in a different way, if the bag with the items is contained in any level below the hotbag (receiver), organiser won't find the items.

To reproduce,  have a scavenger agent set to send easter eggs to a bag inside the backpack (together with everything else that gets scavenged/looted). When trying to organise the easter eggs to first level of backpack, organiser finds 0 items.

It will work if the receiver hot bag is not contained within the hot bag hierarchy.

**Comment by markdwags** [comment] 2020-04-09 01:17
I'm not sure this is a bug -- I believe Razor has only ever organized the top pack only.  I'd have to confirm looking at the older code base.

**Comment by dissident76** [comment] 2020-04-12 01:41
it probably did the same in the older code base, but I think it would be good if we could change that (organise from one bag to another)

**Comment by Saralise** [comment] 2020-10-02 01:14
I've noticed this happen on occasion with organizer.   Also with restocking from top level bags, with containing bags.  Open the sub bags and bags within bags one time before doing it.   A little more work, but it does the trick for me. 

I do that with restock on corpse containers.   Open corpse container, open all sub containers recursively (manually), then do your restock on the top container and it will see everything and clean the corpse. Even if you close em all out before doing the restock.  Saves me from having to drill down manually and restock on every bag.

Edit:  Of course I'm talking about moving the contents of every sub bag, I don't have the bags themselves as items to be restocked.   With organizer, I've seen it ignore the contents of my sub bags unless I open each bags once.  Same principle I think.  That happens only once in a blue moon though with organizer.

**Comment by sorsarre** [comment] 2021-11-22 11:39
I see the recursion in organizer alrighty. The issue here I think has something to do with the search recursion during container update that low-key opens all stuff recursively without showing gumps not getting triggered for backpack upon logging in, so razor can't find the stuff unless you open it manually at least once in the session.

**Comment by markdwags** [comment] 2023-02-18 14:36
Closing for now, will open again if the issue is revisited.

**Closed as not planned by markdwags** 2023-02-18 14:36 UTC
Labels: bug, researching
